

spring.application.name=task-management-project
spring.datasource.url=jdbc:postgresql://localhost:5432/task-management-database
spring.datasource.username=alin
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.deserialization.fail-on-unknown-properties=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

logging.level.com.alin.task_management_project=DEBUG